# -*- coding: utf-8 -*-
"""fewshot_finegrained_cvpr

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JcYVkXrLxyyEU2Up5Eka6fEvUQDkILCl
"""

# ============================================================
# CELL 1: ENVIRONMENT SETUP
# ============================================================

# Mount Google Drive (to save progress permanently)
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

# Create project folder on Google Drive (persistent storage)
import os

PROJECT_DIR = '/content/drive/MyDrive/fewshot_finegrained'
DIRS = ['data', 'features', 'results', 'figures', 'paper']

for d in DIRS:
    os.makedirs(os.path.join(PROJECT_DIR, d), exist_ok=True)
    print(f"✅ Created: {PROJECT_DIR}/{d}")

# Also create local working directory (faster I/O)
LOCAL_DIR = '/content/fewshot_finegrained'
for d in DIRS:
    os.makedirs(os.path.join(LOCAL_DIR, d), exist_ok=True)

print("\n📁 Project structure created!")
print(f"   Google Drive (persistent): {PROJECT_DIR}")
print(f"   Local (fast, temporary):   {LOCAL_DIR}")

# Commented out IPython magic to ensure Python compatibility.
# # ============================================================
# # CELL 2: INSTALL PACKAGES
# # ============================================================
# 
# %%capture install_output
# 
# !pip install torch torchvision torchaudio
# !pip install timm==1.0.3
# !pip install transformers==4.44.0
# !pip install open_clip_torch==2.26.1
# !pip install scikAit-learn==1.5.1
# !pip install matplotlib==3.9.1
# !pip install seaborn==0.13.2
# !pip install pandas==2.2.2
# !pip install tqdm
# !pip install gdown  # for downloading datasets
# 
# print("✅ All packages installed!")

# ============================================================
# CELL 3: VERIFY INSTALLATION (FIXED)
# ============================================================

import torch
import timm
import transformers
import open_clip
import sklearn
import matplotlib
import numpy as np
import pandas as pd

print("=" * 50)
print("ENVIRONMENT CHECK")
print("=" * 50)

# Check GPU
if torch.cuda.is_available():
    gpu_name = torch.cuda.get_device_name(0)
    gpu_mem = torch.cuda.get_device_properties(0).total_memory / 1e9
    print(f"✅ GPU: {gpu_name} ({gpu_mem:.1f} GB)")
else:
    print("❌ NO GPU DETECTED — go to Runtime → Change runtime type → T4 GPU")

# Check packages
print(f"✅ PyTorch:       {torch.__version__}")
print(f"✅ timm:          {timm.__version__}")
print(f"✅ transformers:  {transformers.__version__}")
print(f"✅ open_clip:     {open_clip.__version__}")
print(f"✅ scikit-learn:  {sklearn.__version__}")
print(f"✅ numpy:         {np.__version__}")

# Check disk space
import shutil
total, used, free = shutil.disk_usage("/content")
print(f"\n💾 Disk: {free/1e9:.1f} GB free / {total/1e9:.1f} GB total")

# Check RAM
import psutil
ram = psutil.virtual_memory()
print(f"🧠 RAM:  {ram.available/1e9:.1f} GB free / {ram.total/1e9:.1f} GB total")

# Quick model loading test
print("\n🔄 Testing model loading...")
try:
    test_model = timm.create_model('vit_base_patch16_224', pretrained=False)
    print("✅ timm model loading works")
    del test_model
except Exception as e:
    print(f"❌ timm error: {e}")

torch.cuda.empty_cache()
print("\n" + "=" * 50)
print("✅ ALL CHECKS PASSED — READY TO START!" if torch.cuda.is_available()
      else "⚠️  FIX GPU ISSUE BEFORE CONTINUING")
print("=" * 50)

# ============================================================
# CELL 4: DOWNLOAD ALL 3 DATASETS AUTOMATICALLY
# ============================================================

import os
import urllib.request
import tarfile
import shutil
from tqdm import tqdm

# Setup directories
DATA_DIR = '/content/fewshot_finegrained/data'
os.makedirs(DATA_DIR, exist_ok=True)

class DownloadProgressBar(tqdm):
    def update_to(self, b=1, bsize=1, tsize=None):
        if tsize is not None:
            self.total = tsize
        self.update(b * bsize - self.n)

def download_url(url, output_path):
    with DownloadProgressBar(unit='B', unit_scale=True, miniters=1, desc=output_path.split('/')[-1]) as t:
        urllib.request.urlretrieve(url, filename=output_path, reporthook=t.update_to)

# ══════════════════════════════════════════════════════════════
# DATASET 1: CUB-200-2011 (Birds)
# ══════════════════════════════════════════════════════════════
print("=" * 60)
print("📥 [1/3] CUB-200-2011 (Birds)")
print("=" * 60)

cub_dir = os.path.join(DATA_DIR, 'CUB_200_2011')

if os.path.exists(cub_dir):
    print("✅ Already exists, skipping download")
else:
    # Download from Caltech
    cub_url = "https://data.caltech.edu/records/65de6-vp158/files/CUB_200_2011.tgz"
    cub_tgz = "/content/CUB_200_2011.tgz"

    print("Downloading CUB-200-2011 (~1.1 GB)...")
    download_url(cub_url, cub_tgz)

    print("Extracting...")
    with tarfile.open(cub_tgz, 'r:gz') as tar:
        tar.extractall(DATA_DIR)

    os.remove(cub_tgz)
    print("✅ CUB-200-2011 downloaded and extracted!")

# Verify
cub_images_dir = os.path.join(cub_dir, 'images')
if os.path.exists(cub_images_dir):
    num_classes = len(os.listdir(cub_images_dir))
    num_images = sum(len(files) for _, _, files in os.walk(cub_images_dir))
    print(f"   📊 {num_classes} classes, {num_images} images")

# ══════════════════════════════════════════════════════════════
# DATASET 2: Oxford Flowers-102
# ══════════════════════════════════════════════════════════════
print("\n" + "=" * 60)
print("📥 [2/3] Oxford Flowers-102")
print("=" * 60)

flowers_dir = os.path.join(DATA_DIR, 'flowers102')

if os.path.exists(os.path.join(flowers_dir, 'jpg')):
    print("✅ Already exists, skipping download")
else:
    os.makedirs(flowers_dir, exist_ok=True)

    # Download images
    print("Downloading images (~350 MB)...")
    flowers_url = "https://www.robots.ox.ac.uk/~vgg/data/flowers/102/102flowers.tgz"
    flowers_tgz = "/content/102flowers.tgz"
    download_url(flowers_url, flowers_tgz)

    # Download labels
    print("Downloading labels...")
    labels_url = "https://www.robots.ox.ac.uk/~vgg/data/flowers/102/imagelabels.mat"
    download_url(labels_url, os.path.join(flowers_dir, 'imagelabels.mat'))

    # Download splits
    print("Downloading splits...")
    splits_url = "https://www.robots.ox.ac.uk/~vgg/data/flowers/102/setid.mat"
    download_url(splits_url, os.path.join(flowers_dir, 'setid.mat'))

    # Extract images
    print("Extracting...")
    with tarfile.open(flowers_tgz, 'r:gz') as tar:
        tar.extractall(flowers_dir)

    os.remove(flowers_tgz)
    print("✅ Flowers-102 downloaded and extracted!")

# Verify
flowers_jpg_dir = os.path.join(flowers_dir, 'jpg')
if os.path.exists(flowers_jpg_dir):
    num_images = len([f for f in os.listdir(flowers_jpg_dir) if f.endswith('.jpg')])
    print(f"   📊 102 classes, {num_images} images")

# ══════════════════════════════════════════════════════════════
# DATASET 3: FGVC-Aircraft
# ══════════════════════════════════════════════════════════════
print("\n" + "=" * 60)
print("📥 [3/3] FGVC-Aircraft")
print("=" * 60)

aircraft_dir = os.path.join(DATA_DIR, 'fgvc_aircraft')

if os.path.exists(os.path.join(aircraft_dir, 'data', 'images')):
    print("✅ Already exists, skipping download")
else:
    os.makedirs(aircraft_dir, exist_ok=True)

    print("Downloading FGVC-Aircraft (~450 MB)...")
    aircraft_url = "https://www.robots.ox.ac.uk/~vgg/data/fgvc-aircraft/archives/fgvc-aircraft-2013b.tar.gz"
    aircraft_tgz = "/content/fgvc-aircraft.tar.gz"
    download_url(aircraft_url, aircraft_tgz)

    print("Extracting...")
    with tarfile.open(aircraft_tgz, 'r:gz') as tar:
        tar.extractall('/content/temp_aircraft')

    # Move to correct location
    extracted_dir = '/content/temp_aircraft/fgvc-aircraft-2013b'
    if os.path.exists(extracted_dir):
        shutil.move(extracted_dir + '/data', aircraft_dir + '/data')
    shutil.rmtree('/content/temp_aircraft', ignore_errors=True)

    os.remove(aircraft_tgz)
    print("✅ FGVC-Aircraft downloaded and extracted!")

# Verify
aircraft_images_dir = os.path.join(aircraft_dir, 'data', 'images')
if os.path.exists(aircraft_images_dir):
    num_images = len([f for f in os.listdir(aircraft_images_dir) if f.endswith('.jpg')])
    print(f"   📊 100 classes, {num_images} images")

# ══════════════════════════════════════════════════════════════
# FINAL SUMMARY
# ══════════════════════════════════════════════════════════════
print("\n" + "=" * 60)
print("📊 DOWNLOAD SUMMARY")
print("=" * 60)

datasets_info = [
    ("CUB-200-2011", os.path.join(DATA_DIR, 'CUB_200_2011', 'images')),
    ("Flowers-102", os.path.join(DATA_DIR, 'flowers102', 'jpg')),
    ("FGVC-Aircraft", os.path.join(DATA_DIR, 'fgvc_aircraft', 'data', 'images'))
]

all_success = True
for name, path in datasets_info:
    if os.path.exists(path):
        if name == "Flowers-102":
            count = len([f for f in os.listdir(path) if f.endswith('.jpg')])
        else:
            count = sum(len([f for f in files if f.lower().endswith(('.jpg', '.jpeg', '.png'))])
                       for _, _, files in os.walk(path))
        print(f"  ✅ {name:20s}: {count:>6d} images")
    else:
        print(f"  ❌ {name:20s}: NOT FOUND")
        all_success = False

# Disk space check
total, used, free = shutil.disk_usage("/content")
print(f"\n💾 Disk space remaining: {free/1e9:.1f} GB")

if all_success:
    print("\n" + "🎉" * 20)
    print("   ALL 3 DATASETS READY! Proceed to feature extraction.")
    print("🎉" * 20)
else:
    print("\n⚠️  Some datasets failed. Check errors above.")

"""## Feature Extraction

Setup Feature Extraction
"""

# ============================================================
# CELL 5: FEATURE EXTRACTION SETUP
# ============================================================

import os
import torch
import torch.nn as nn
import numpy as np
from PIL import Image
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from tqdm import tqdm
import timm
import gc
import scipy.io

# Paths
DATA_DIR = '/content/fewshot_finegrained/data'
FEATURES_DIR = '/content/drive/MyDrive/fewshot_finegrained/features'
os.makedirs(FEATURES_DIR, exist_ok=True)

# Device
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"🖥️  Device: {device}")

# ══════════════════════════════════════════════════════════════
# IMAGE TRANSFORMS (Standard ImageNet preprocessing)
# ══════════════════════════════════════════════════════════════
transform = transforms.Compose([
    transforms.Resize(256),
    transforms.CenterCrop(224),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                         std=[0.229, 0.224, 0.225])
])

# ══════════════════════════════════════════════════════════════
# DATASET CLASSES
# ══════════════════════════════════════════════════════════════

class CUBDataset(Dataset):
    """CUB-200-2011 Dataset"""
    def __init__(self, root, transform=None):
        self.root = root
        self.transform = transform

        # Load image paths and labels
        images_file = os.path.join(root, 'images.txt')
        labels_file = os.path.join(root, 'image_class_labels.txt')

        with open(images_file, 'r') as f:
            self.images = [line.strip().split(' ')[1] for line in f]

        with open(labels_file, 'r') as f:
            self.labels = [int(line.strip().split(' ')[1]) - 1 for line in f]  # 0-indexed

        print(f"   CUB: {len(self.images)} images, {len(set(self.labels))} classes")

    def __len__(self):
        return len(self.images)

    def __getitem__(self, idx):
        img_path = os.path.join(self.root, 'images', self.images[idx])
        image = Image.open(img_path).convert('RGB')
        if self.transform:
            image = self.transform(image)
        return image, self.labels[idx], idx


class FlowersDataset(Dataset):
    """Oxford Flowers-102 Dataset"""
    def __init__(self, root, transform=None):
        self.root = root
        self.transform = transform

        # Load labels from .mat file
        labels_mat = scipy.io.loadmat(os.path.join(root, 'imagelabels.mat'))
        self.labels = labels_mat['labels'][0] - 1  # 0-indexed

        # Image files are named image_00001.jpg to image_08189.jpg
        self.images = [f'image_{i:05d}.jpg' for i in range(1, len(self.labels) + 1)]

        print(f"   Flowers: {len(self.images)} images, {len(set(self.labels))} classes")

    def __len__(self):
        return len(self.images)

    def __getitem__(self, idx):
        img_path = os.path.join(self.root, 'jpg', self.images[idx])
        image = Image.open(img_path).convert('RGB')
        if self.transform:
            image = self.transform(image)
        return image, int(self.labels[idx]), idx


class AircraftDataset(Dataset):
    """FGVC-Aircraft Dataset"""
    def __init__(self, root, transform=None):
        self.root = root
        self.transform = transform
        self.images_dir = os.path.join(root, 'data', 'images')

        # Load all variants (most fine-grained level)
        variants_file = os.path.join(root, 'data', 'variants.txt')
        with open(variants_file, 'r') as f:
            variants = [line.strip() for line in f]
        self.variant_to_idx = {v: i for i, v in enumerate(variants)}

        # Load all images and labels from trainval + test
        self.images = []
        self.labels = []

        for split in ['images_variant_trainval.txt', 'images_variant_test.txt']:
            split_file = os.path.join(root, 'data', split)
            if os.path.exists(split_file):
                with open(split_file, 'r') as f:
                    for line in f:
                        parts = line.strip().split(' ', 1)
                        img_name = parts[0] + '.jpg'
                        variant = parts[1]
                        self.images.append(img_name)
                        self.labels.append(self.variant_to_idx[variant])

        print(f"   Aircraft: {len(self.images)} images, {len(set(self.labels))} classes")

    def __len__(self):
        return len(self.images)

    def __getitem__(self, idx):
        img_path = os.path.join(self.images_dir, self.images[idx])
        image = Image.open(img_path).convert('RGB')
        if self.transform:
            image = self.transform(image)
        return image, self.labels[idx], idx


# ══════════════════════════════════════════════════════════════
# LOAD ALL DATASETS
# ══════════════════════════════════════════════════════════════
print("\n📁 Loading datasets...")

datasets = {
    'cub': CUBDataset(
        os.path.join(DATA_DIR, 'CUB_200_2011'),
        transform=transform
    ),
    'flowers': FlowersDataset(
        os.path.join(DATA_DIR, 'flowers102'),
        transform=transform
    ),
    'aircraft': AircraftDataset(
        os.path.join(DATA_DIR, 'fgvc_aircraft'),
        transform=transform
    )
}

print("\n✅ All datasets loaded successfully!")
print(f"   Total images to process: {sum(len(d) for d in datasets.values()):,}")

"""Define Backbone Models"""

# ============================================================
# CELL 6: DEFINE BACKBONE MODELS TO USE
# ============================================================

# Backbones we will extract features from
BACKBONES = {
    # ─────────────────────────────────────────────────────────
    # DINOv2 (Self-supervised, 2023) - STRONGEST for few-shot
    # ─────────────────────────────────────────────────────────
    'dinov2_vitb14': {
        'source': 'torch_hub',
        'name': 'dinov2_vitb14',
        'repo': 'facebookresearch/dinov2',
        'feat_dim': 768
    },

    # ─────────────────────────────────────────────────────────
    # CLIP (Language-supervised, OpenAI)
    # ─────────────────────────────────────────────────────────
    'clip_vitb16': {
        'source': 'open_clip',
        'name': 'ViT-B-16',
        'pretrained': 'openai',
        'feat_dim': 512
    },

    # ─────────────────────────────────────────────────────────
    # Supervised baseline (ImageNet-21K pretrained)
    # ─────────────────────────────────────────────────────────
    'vit_base_patch16_224_in21k': {
        'source': 'timm',
        'name': 'vit_base_patch16_224.augreg_in21k',
        'feat_dim': 768
    },

    # ─────────────────────────────────────────────────────────
    # ResNet50 (Classic CNN baseline)
    # ─────────────────────────────────────────────────────────
    'resnet50': {
        'source': 'timm',
        'name': 'resnet50.a1_in1k',
        'feat_dim': 2048
    },
}

print("🧠 Backbones to extract:")
print("=" * 50)
for name, config in BACKBONES.items():
    print(f"   • {name:30s} (dim={config['feat_dim']})")
print("=" * 50)
print(f"   Total: {len(BACKBONES)} backbones × {len(datasets)} datasets")
print(f"   = {len(BACKBONES) * len(datasets)} feature extraction runs")

"""Feature Extraction Function"""

# ============================================================
# CELL 7: FEATURE EXTRACTION FUNCTION
# ============================================================

def load_backbone(config):
    """Load a backbone model based on config."""

    if config['source'] == 'torch_hub':
        model = torch.hub.load(config['repo'], config['name'])
        model.eval()
        return model

    elif config['source'] == 'open_clip':
        import open_clip
        model, _, preprocess = open_clip.create_model_and_transforms(
            config['name'],
            pretrained=config['pretrained']
        )
        model.eval()
        # Return only the visual encoder
        return model.visual

    elif config['source'] == 'timm':
        model = timm.create_model(config['name'], pretrained=True, num_classes=0)
        model.eval()
        return model

    else:
        raise ValueError(f"Unknown source: {config['source']}")


@torch.no_grad()
def extract_features(model, dataloader, device, backbone_name):
    """Extract features from all images using the given model."""

    all_features = []
    all_labels = []
    all_indices = []

    model = model.to(device)
    model.eval()

    for images, labels, indices in tqdm(dataloader, desc=f"   Extracting"):
        images = images.to(device)

        # Forward pass
        if 'dinov2' in backbone_name:
            # DINOv2 returns class token by default
            features = model(images)
        elif 'clip' in backbone_name:
            # CLIP visual encoder
            features = model(images)
        else:
            # timm models with num_classes=0 return features directly
            features = model(images)

        all_features.append(features.cpu().numpy())
        all_labels.extend(labels.numpy())
        all_indices.extend(indices.numpy())

    features = np.concatenate(all_features, axis=0)
    labels = np.array(all_labels)
    indices = np.array(all_indices)

    return features, labels, indices


def save_features(features, labels, indices, backbone_name, dataset_name, save_dir):
    """Save extracted features to disk."""

    save_path = os.path.join(save_dir, f"{backbone_name}_{dataset_name}.npz")
    np.savez_compressed(
        save_path,
        features=features,
        labels=labels,
        indices=indices
    )
    size_mb = os.path.getsize(save_path) / 1e6
    print(f"   💾 Saved: {save_path} ({size_mb:.1f} MB)")
    return save_path


def clear_gpu_memory():
    """Clear GPU memory."""
    gc.collect()
    torch.cuda.empty_cache()
    if torch.cuda.is_available():
        torch.cuda.synchronize()

print("✅ Feature extraction functions defined!")

"""Run Feature Extraction (THE BIG ONE)"""

# ============================================================
# CELL 8: EXTRACT FEATURES FROM ALL BACKBONES × ALL DATASETS
# ============================================================

import time

BATCH_SIZE = 64  # Adjust if you get OOM errors
NUM_WORKERS = 2

print("=" * 60)
print("🚀 STARTING FEATURE EXTRACTION")
print("=" * 60)
print(f"   Batch size: {BATCH_SIZE}")
print(f"   Save directory: {FEATURES_DIR}")
print("=" * 60)

total_start = time.time()
extraction_log = []

for backbone_name, backbone_config in BACKBONES.items():

    print(f"\n{'='*60}")
    print(f"🧠 BACKBONE: {backbone_name}")
    print(f"{'='*60}")

    # Check if all datasets already extracted for this backbone
    all_exist = all(
        os.path.exists(os.path.join(FEATURES_DIR, f"{backbone_name}_{ds_name}.npz"))
        for ds_name in datasets.keys()
    )

    if all_exist:
        print(f"   ⏭️  All features already exist, skipping...")
        continue

    # Load backbone
    print(f"   📥 Loading model...")
    backbone_start = time.time()

    try:
        model = load_backbone(backbone_config)
        model = model.to(device)
        print(f"   ✅ Model loaded in {time.time() - backbone_start:.1f}s")
    except Exception as e:
        print(f"   ❌ Failed to load: {e}")
        continue

    # Extract features for each dataset
    for dataset_name, dataset in datasets.items():

        save_path = os.path.join(FEATURES_DIR, f"{backbone_name}_{dataset_name}.npz")

        if os.path.exists(save_path):
            print(f"\n   📂 {dataset_name}: Already exists, skipping...")
            continue

        print(f"\n   📂 {dataset_name}: Extracting features...")

        dataloader = DataLoader(
            dataset,
            batch_size=BATCH_SIZE,
            shuffle=False,
            num_workers=NUM_WORKERS,
            pin_memory=True
        )

        extract_start = time.time()
        features, labels, indices = extract_features(
            model, dataloader, device, backbone_name
        )
        extract_time = time.time() - extract_start

        print(f"   ✅ Extracted: {features.shape} in {extract_time:.1f}s")

        # Save to Drive
        save_features(features, labels, indices, backbone_name, dataset_name, FEATURES_DIR)

        extraction_log.append({
            'backbone': backbone_name,
            'dataset': dataset_name,
            'shape': features.shape,
            'time': extract_time
        })

    # Clear GPU memory before loading next backbone
    del model
    clear_gpu_memory()
    print(f"\n   🧹 GPU memory cleared")

total_time = time.time() - total_start

# ══════════════════════════════════════════════════════════════
# FINAL SUMMARY
# ══════════════════════════════════════════════════════════════
print("\n" + "=" * 60)
print("📊 FEATURE EXTRACTION COMPLETE!")
print("=" * 60)

# List all saved files
print("\n📁 Saved feature files:")
for f in sorted(os.listdir(FEATURES_DIR)):
    if f.endswith('.npz'):
        size = os.path.getsize(os.path.join(FEATURES_DIR, f)) / 1e6
        print(f"   ✅ {f} ({size:.1f} MB)")

print(f"\n⏱️  Total time: {total_time/60:.1f} minutes")
print(f"💾 Features saved to: {FEATURES_DIR}")

# Verify all expected files exist
expected_files = [
    f"{b}_{d}.npz"
    for b in BACKBONES.keys()
    for d in datasets.keys()
]
missing = [f for f in expected_files if not os.path.exists(os.path.join(FEATURES_DIR, f))]

if missing:
    print(f"\n⚠️  Missing files: {missing}")
else:
    print("\n🎉 ALL FEATURES EXTRACTED SUCCESSFULLY!")
    print("   You can now close this session.")
    print("   Features are safely saved to Google Drive.")

"""## Classification Experiments

Features & Define Few-Shot Evaluation
"""

# ============================================================
# CELL 9: FEW-SHOT EVALUATION SETUP
# ============================================================

import os
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import normalize
from sklearn.metrics import accuracy_score
from scipy.stats import sem
import time
import pandas as pd
from tqdm import tqdm
import warnings
warnings.filterwarnings('ignore')

# Mount Drive (if not already mounted)
from google.colab import drive
drive.mount('/content/drive', force_remount=False)

# Paths
FEATURES_DIR = '/content/drive/MyDrive/fewshot_finegrained/features'
RESULTS_DIR = '/content/drive/MyDrive/fewshot_finegrained/results'
os.makedirs(RESULTS_DIR, exist_ok=True)

# ══════════════════════════════════════════════════════════════
# LOAD ALL FEATURES
# ══════════════════════════════════════════════════════════════
print("📂 Loading extracted features...")
print("=" * 60)

features_data = {}

for f in sorted(os.listdir(FEATURES_DIR)):
    if f.endswith('.npz'):
        path = os.path.join(FEATURES_DIR, f)
        data = np.load(path)

        # Parse filename: backbone_dataset.npz
        name = f.replace('.npz', '')
        parts = name.rsplit('_', 1)

        # Handle multi-part backbone names
        if parts[-1] in ['cub', 'flowers', 'aircraft']:
            dataset = parts[-1]
            backbone = name.replace(f'_{dataset}', '')
        else:
            # Fallback
            backbone = '_'.join(parts[:-1])
            dataset = parts[-1]

        features_data[(backbone, dataset)] = {
            'features': data['features'],
            'labels': data['labels'],
        }

        print(f"   ✅ {backbone:35s} | {dataset:10s} | shape: {data['features'].shape}")

print("=" * 60)
print(f"✅ Loaded {len(features_data)} feature sets")

# ══════════════════════════════════════════════════════════════
# FEW-SHOT EPISODE EVALUATION
# ══════════════════════════════════════════════════════════════

def create_few_shot_episode(features, labels, n_way, k_shot, n_query=15):
    """
    Create a single few-shot episode.

    Args:
        features: All features [N, D]
        labels: All labels [N]
        n_way: Number of classes per episode
        k_shot: Number of support examples per class
        n_query: Number of query examples per class

    Returns:
        support_X, support_y, query_X, query_y
    """
    unique_classes = np.unique(labels)

    # Sample n_way classes
    selected_classes = np.random.choice(unique_classes, n_way, replace=False)

    support_X, support_y = [], []
    query_X, query_y = [], []

    for new_label, cls in enumerate(selected_classes):
        # Get all indices for this class
        cls_indices = np.where(labels == cls)[0]

        # Ensure we have enough samples
        if len(cls_indices) < k_shot + n_query:
            # If not enough samples, sample with replacement for query
            chosen = np.random.choice(cls_indices, k_shot + n_query, replace=True)
        else:
            chosen = np.random.choice(cls_indices, k_shot + n_query, replace=False)

        support_idx = chosen[:k_shot]
        query_idx = chosen[k_shot:k_shot + n_query]

        support_X.append(features[support_idx])
        support_y.extend([new_label] * k_shot)
        query_X.append(features[query_idx])
        query_y.extend([new_label] * len(query_idx))

    return (np.concatenate(support_X), np.array(support_y),
            np.concatenate(query_X), np.array(query_y))


def evaluate_few_shot(features, labels, n_way, k_shot, n_query,
                      n_episodes, classifier_type='lr'):
    """
    Evaluate few-shot classification over multiple episodes.

    Args:
        classifier_type: 'lr' (logistic regression), 'ncc' (nearest class centroid),
                         'knn' (k-nearest neighbors)
    """
    accuracies = []

    for _ in range(n_episodes):
        support_X, support_y, query_X, query_y = create_few_shot_episode(
            features, labels, n_way, k_shot, n_query
        )

        # L2 normalize features (important for cosine-based methods)
        support_X = normalize(support_X)
        query_X = normalize(query_X)

        if classifier_type == 'ncc':
            # Nearest Class Centroid (Prototypical Networks style)
            centroids = []
            for c in range(n_way):
                class_features = support_X[support_y == c]
                centroids.append(class_features.mean(axis=0))
            centroids = np.array(centroids)
            centroids = normalize(centroids)

            # Cosine similarity (equivalent to dot product after normalization)
            similarities = query_X @ centroids.T
            preds = similarities.argmax(axis=1)

        elif classifier_type == 'lr':
            # Logistic Regression
            clf = LogisticRegression(
                C=10.0,
                max_iter=1000,
                solver='lbfgs',
                multi_class='multinomial',
                random_state=42
            )
            clf.fit(support_X, support_y)
            preds = clf.predict(query_X)

        elif classifier_type == 'knn':
            # K-Nearest Neighbors
            k = min(5, k_shot)  # Can't have more neighbors than support examples
            clf = KNeighborsClassifier(n_neighbors=k, metric='cosine')
            clf.fit(support_X, support_y)
            preds = clf.predict(query_X)

        else:
            raise ValueError(f"Unknown classifier: {classifier_type}")

        acc = accuracy_score(query_y, preds)
        accuracies.append(acc)

    mean_acc = np.mean(accuracies) * 100
    std_acc = np.std(accuracies) * 100
    ci95 = 1.96 * sem(accuracies) * 100

    return mean_acc, std_acc, ci95


print("\n✅ Few-shot evaluation functions defined!")
print("   Ready to run experiments.")

"""ALL Experiments"""

# ============================================================
# CELL 10: RUN ALL FEW-SHOT EXPERIMENTS
# ============================================================

# Experiment Configuration
CONFIG = {
    'n_way': 5,           # 5-way classification (standard)
    'n_query': 15,        # 15 query images per class (standard)
    'n_episodes': 600,    # 600 episodes for reliable confidence intervals
    'k_shots': [1, 5, 10, 20],  # Different shot settings
    'classifiers': ['ncc', 'lr', 'knn'],  # All classifier types
}

# Backbones and datasets to evaluate
BACKBONES = ['dinov2_vitb14', 'clip_vitb16', 'vit_base_patch16_224_in21k', 'resnet50']
DATASETS = ['cub', 'flowers', 'aircraft']

print("=" * 70)
print("🚀 RUNNING FEW-SHOT EXPERIMENTS")
print("=" * 70)
print(f"   Configuration:")
print(f"   • {CONFIG['n_way']}-way classification")
print(f"   • {CONFIG['n_episodes']} episodes per setting")
print(f"   • k-shots: {CONFIG['k_shots']}")
print(f"   • Classifiers: {CONFIG['classifiers']}")
print(f"   • Backbones: {len(BACKBONES)}")
print(f"   • Datasets: {len(DATASETS)}")
print("=" * 70)

total_experiments = (len(BACKBONES) * len(DATASETS) *
                     len(CONFIG['k_shots']) * len(CONFIG['classifiers']))
print(f"   Total experiments: {total_experiments}")
print("=" * 70)

# Store all results
all_results = []

total_start = time.time()
exp_count = 0

for dataset in DATASETS:
    print(f"\n{'='*70}")
    print(f"📊 DATASET: {dataset.upper()}")
    print(f"{'='*70}")

    for backbone in BACKBONES:
        key = (backbone, dataset)

        if key not in features_data:
            print(f"   ⚠️  Missing: {backbone} × {dataset}")
            continue

        features = features_data[key]['features']
        labels = features_data[key]['labels']

        print(f"\n   🧠 {backbone}")

        for k_shot in CONFIG['k_shots']:
            for clf_type in CONFIG['classifiers']:
                exp_count += 1

                # Run evaluation
                start = time.time()
                mean_acc, std_acc, ci95 = evaluate_few_shot(
                    features=features,
                    labels=labels,
                    n_way=CONFIG['n_way'],
                    k_shot=k_shot,
                    n_query=CONFIG['n_query'],
                    n_episodes=CONFIG['n_episodes'],
                    classifier_type=clf_type
                )
                elapsed = time.time() - start

                # Store result
                result = {
                    'backbone': backbone,
                    'dataset': dataset,
                    'k_shot': k_shot,
                    'classifier': clf_type,
                    'accuracy': mean_acc,
                    'std': std_acc,
                    'ci95': ci95,
                    'time': elapsed
                }
                all_results.append(result)

                print(f"      {k_shot:2d}-shot | {clf_type:3s}: {mean_acc:5.2f}% ± {ci95:.2f}%  ({elapsed:.1f}s)")

total_time = time.time() - total_start

# ══════════════════════════════════════════════════════════════
# SAVE RESULTS
# ══════════════════════════════════════════════════════════════
results_df = pd.DataFrame(all_results)
results_path = os.path.join(RESULTS_DIR, 'fewshot_results.csv')
results_df.to_csv(results_path, index=False)

print("\n" + "=" * 70)
print("📊 EXPERIMENTS COMPLETE!")
print("=" * 70)
print(f"   Total experiments: {exp_count}")
print(f"   Total time: {total_time/60:.1f} minutes")
print(f"   Results saved: {results_path}")
print("=" * 70)

# ============================================================
# CELL 11: DISPLAY RESULTS AS TABLES
# ============================================================

import pandas as pd

# Load results
results_df = pd.read_csv(os.path.join(RESULTS_DIR, 'fewshot_results.csv'))

# ══════════════════════════════════════════════════════════════
# TABLE 1: Best classifier per backbone (using Logistic Regression)
# ══════════════════════════════════════════════════════════════

print("=" * 80)
print("📊 TABLE 1: Few-Shot Accuracy (%) — Logistic Regression Classifier")
print("=" * 80)

for dataset in ['cub', 'flowers', 'aircraft']:
    print(f"\n{'─'*80}")
    print(f"Dataset: {dataset.upper()}")
    print(f"{'─'*80}")

    # Filter for this dataset and LR classifier
    df_subset = results_df[(results_df['dataset'] == dataset) &
                           (results_df['classifier'] == 'lr')]

    # Pivot table
    pivot = df_subset.pivot(index='backbone', columns='k_shot', values='accuracy')
    pivot_ci = df_subset.pivot(index='backbone', columns='k_shot', values='ci95')

    # Format with confidence intervals
    print(f"\n{'Backbone':<40} {'1-shot':>12} {'5-shot':>12} {'10-shot':>12} {'20-shot':>12}")
    print("-" * 80)

    for backbone in pivot.index:
        row = f"{backbone:<40}"
        for k in [1, 5, 10, 20]:
            acc = pivot.loc[backbone, k]
            ci = pivot_ci.loc[backbone, k]
            row += f" {acc:>5.2f}±{ci:<4.2f}"
        print(row)

# ══════════════════════════════════════════════════════════════
# TABLE 2: Compare classifiers for best backbone (DINOv2)
# ══════════════════════════════════════════════════════════════

print("\n" + "=" * 80)
print("📊 TABLE 2: Classifier Comparison (DINOv2-ViT-B/14)")
print("=" * 80)

for dataset in ['cub', 'flowers', 'aircraft']:
    print(f"\n{'─'*80}")
    print(f"Dataset: {dataset.upper()}")
    print(f"{'─'*80}")

    df_subset = results_df[(results_df['dataset'] == dataset) &
                           (results_df['backbone'] == 'dinov2_vitb14')]

    pivot = df_subset.pivot(index='classifier', columns='k_shot', values='accuracy')

    print(f"\n{'Classifier':<15} {'1-shot':>12} {'5-shot':>12} {'10-shot':>12} {'20-shot':>12}")
    print("-" * 60)

    for clf in ['ncc', 'lr', 'knn']:
        if clf in pivot.index:
            row = f"{clf.upper():<15}"
            for k in [1, 5, 10, 20]:
                acc = pivot.loc[clf, k]
                row += f" {acc:>10.2f}%"
            print(row)

# ══════════════════════════════════════════════════════════════
# SUMMARY: Best results per dataset
# ══════════════════════════════════════════════════════════════

print("\n" + "=" * 80)
print("🏆 BEST RESULTS SUMMARY")
print("=" * 80)

for dataset in ['cub', 'flowers', 'aircraft']:
    df_subset = results_df[results_df['dataset'] == dataset]

    print(f"\n{dataset.upper()}:")
    for k in [1, 5]:
        best_row = df_subset[df_subset['k_shot'] == k].loc[
            df_subset[df_subset['k_shot'] == k]['accuracy'].idxmax()
        ]
        print(f"   {k}-shot best: {best_row['accuracy']:.2f}% "
              f"({best_row['backbone']} + {best_row['classifier'].upper()})")

"""## Figures"""

# ============================================================
# CELL 12: GENERATE PUBLICATION-QUALITY FIGURES
# ============================================================

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd
import os

# Settings
plt.rcParams['font.size'] = 12
plt.rcParams['axes.labelsize'] = 14
plt.rcParams['axes.titlesize'] = 14
plt.rcParams['legend.fontsize'] = 11
plt.rcParams['figure.dpi'] = 150
plt.rcParams['savefig.dpi'] = 300
plt.rcParams['font.family'] = 'sans-serif'

# Load results
RESULTS_DIR = '/content/drive/MyDrive/fewshot_finegrained/results'
FIGURES_DIR = '/content/drive/MyDrive/fewshot_finegrained/figures'
os.makedirs(FIGURES_DIR, exist_ok=True)

results_df = pd.read_csv(os.path.join(RESULTS_DIR, 'fewshot_results.csv'))

# Color palette
COLORS = {
    'dinov2_vitb14': '#2ecc71',           # Green
    'clip_vitb16': '#3498db',              # Blue
    'vit_base_patch16_224_in21k': '#9b59b6',  # Purple
    'resnet50': '#e74c3c',                 # Red
}

BACKBONE_NAMES = {
    'dinov2_vitb14': 'DINOv2-ViT-B/14',
    'clip_vitb16': 'CLIP-ViT-B/16',
    'vit_base_patch16_224_in21k': 'ViT-B/16-IN21K',
    'resnet50': 'ResNet-50',
}

DATASET_NAMES = {
    'cub': 'CUB-200-2011',
    'flowers': 'Flowers-102',
    'aircraft': 'FGVC-Aircraft',
}

# ══════════════════════════════════════════════════════════════
# FIGURE 1: Main Results — Accuracy vs Shots (3 subplots)
# ══════════════════════════════════════════════════════════════

fig, axes = plt.subplots(1, 3, figsize=(14, 4))

for idx, dataset in enumerate(['cub', 'flowers', 'aircraft']):
    ax = axes[idx]

    df_subset = results_df[(results_df['dataset'] == dataset) &
                           (results_df['classifier'] == 'lr')]

    for backbone in COLORS.keys():
        df_backbone = df_subset[df_subset['backbone'] == backbone]
        df_backbone = df_backbone.sort_values('k_shot')

        ax.errorbar(
            df_backbone['k_shot'],
            df_backbone['accuracy'],
            yerr=df_backbone['ci95'],
            marker='o',
            markersize=8,
            linewidth=2,
            capsize=4,
            color=COLORS[backbone],
            label=BACKBONE_NAMES[backbone]
        )

    ax.set_xlabel('Number of Shots (k)')
    ax.set_ylabel('Accuracy (%)')
    ax.set_title(DATASET_NAMES[dataset])
    ax.set_xticks([1, 5, 10, 20])
    ax.grid(True, alpha=0.3)
    ax.set_ylim([40, 102])

    if idx == 0:
        ax.legend(loc='lower right')

plt.tight_layout()
fig_path = os.path.join(FIGURES_DIR, 'fig1_main_results.pdf')
plt.savefig(fig_path, bbox_inches='tight')
plt.savefig(fig_path.replace('.pdf', '.png'), bbox_inches='tight')
print(f"✅ Saved: {fig_path}")
plt.show()

# ══════════════════════════════════════════════════════════════
# FIGURE 2: Backbone Comparison Bar Chart (1-shot and 5-shot)
# ══════════════════════════════════════════════════════════════

fig, axes = plt.subplots(1, 2, figsize=(12, 5))

for idx, k_shot in enumerate([1, 5]):
    ax = axes[idx]

    df_subset = results_df[(results_df['k_shot'] == k_shot) &
                           (results_df['classifier'] == 'lr')]

    x = np.arange(len(DATASET_NAMES))
    width = 0.2

    for i, backbone in enumerate(COLORS.keys()):
        df_backbone = df_subset[df_subset['backbone'] == backbone]
        accuracies = [df_backbone[df_backbone['dataset'] == d]['accuracy'].values[0]
                      for d in ['cub', 'flowers', 'aircraft']]
        ci95s = [df_backbone[df_backbone['dataset'] == d]['ci95'].values[0]
                 for d in ['cub', 'flowers', 'aircraft']]

        ax.bar(x + i * width, accuracies, width,
               yerr=ci95s, capsize=3,
               label=BACKBONE_NAMES[backbone],
               color=COLORS[backbone], alpha=0.85)

    ax.set_xlabel('Dataset')
    ax.set_ylabel('Accuracy (%)')
    ax.set_title(f'{k_shot}-Shot Classification')
    ax.set_xticks(x + width * 1.5)
    ax.set_xticklabels([DATASET_NAMES[d] for d in ['cub', 'flowers', 'aircraft']])
    ax.set_ylim([35, 105])
    ax.grid(True, alpha=0.3, axis='y')

    if idx == 0:
        ax.legend(loc='lower left')

plt.tight_layout()
fig_path = os.path.join(FIGURES_DIR, 'fig2_backbone_comparison.pdf')
plt.savefig(fig_path, bbox_inches='tight')
plt.savefig(fig_path.replace('.pdf', '.png'), bbox_inches='tight')
print(f"✅ Saved: {fig_path}")
plt.show()

# ══════════════════════════════════════════════════════════════
# FIGURE 3: Classifier Comparison (DINOv2 only)
# ══════════════════════════════════════════════════════════════

fig, axes = plt.subplots(1, 3, figsize=(14, 4))

clf_colors = {'ncc': '#1abc9c', 'lr': '#3498db', 'knn': '#e67e22'}
clf_names = {'ncc': 'Nearest Centroid', 'lr': 'Logistic Regression', 'knn': 'k-NN'}

for idx, dataset in enumerate(['cub', 'flowers', 'aircraft']):
    ax = axes[idx]

    df_subset = results_df[(results_df['dataset'] == dataset) &
                           (results_df['backbone'] == 'dinov2_vitb14')]

    for clf in ['ncc', 'lr', 'knn']:
        df_clf = df_subset[df_subset['classifier'] == clf]
        df_clf = df_clf.sort_values('k_shot')

        ax.plot(
            df_clf['k_shot'],
            df_clf['accuracy'],
            marker='s',
            markersize=8,
            linewidth=2,
            color=clf_colors[clf],
            label=clf_names[clf]
        )

    ax.set_xlabel('Number of Shots (k)')
    ax.set_ylabel('Accuracy (%)')
    ax.set_title(f'{DATASET_NAMES[dataset]} (DINOv2)')
    ax.set_xticks([1, 5, 10, 20])
    ax.grid(True, alpha=0.3)

    if dataset == 'aircraft':
        ax.set_ylim([60, 95])
    else:
        ax.set_ylim([95, 100.5])

    if idx == 0:
        ax.legend(loc='lower right')

plt.tight_layout()
fig_path = os.path.join(FIGURES_DIR, 'fig3_classifier_comparison.pdf')
plt.savefig(fig_path, bbox_inches='tight')
plt.savefig(fig_path.replace('.pdf', '.png'), bbox_inches='tight')
print(f"✅ Saved: {fig_path}")
plt.show()

# ══════════════════════════════════════════════════════════════
# FIGURE 4: Heatmap — All Results Summary
# ══════════════════════════════════════════════════════════════

fig, axes = plt.subplots(1, 2, figsize=(12, 4))

for idx, k_shot in enumerate([1, 5]):
    ax = axes[idx]

    df_subset = results_df[(results_df['k_shot'] == k_shot) &
                           (results_df['classifier'] == 'lr')]

    # Create pivot table
    pivot = df_subset.pivot(index='backbone', columns='dataset', values='accuracy')
    pivot = pivot.rename(index=BACKBONE_NAMES, columns=DATASET_NAMES)
    pivot = pivot[['CUB-200-2011', 'Flowers-102', 'FGVC-Aircraft']]
    pivot = pivot.reindex(['DINOv2-ViT-B/14', 'CLIP-ViT-B/16',
                           'ViT-B/16-IN21K', 'ResNet-50'])

    sns.heatmap(
        pivot,
        annot=True,
        fmt='.1f',
        cmap='RdYlGn',
        vmin=40,
        vmax=100,
        ax=ax,
        cbar_kws={'label': 'Accuracy (%)'}
    )

    ax.set_title(f'{k_shot}-Shot Classification')
    ax.set_xlabel('')
    ax.set_ylabel('')

plt.tight_layout()
fig_path = os.path.join(FIGURES_DIR, 'fig4_heatmap.pdf')
plt.savefig(fig_path, bbox_inches='tight')
plt.savefig(fig_path.replace('.pdf', '.png'), bbox_inches='tight')
print(f"✅ Saved: {fig_path}")
plt.show()

# ══════════════════════════════════════════════════════════════
# FIGURE 5: Improvement over ResNet-50 baseline
# ══════════════════════════════════════════════════════════════

fig, ax = plt.subplots(figsize=(10, 5))

df_5shot = results_df[(results_df['k_shot'] == 5) &
                      (results_df['classifier'] == 'lr')]

datasets = ['cub', 'flowers', 'aircraft']
x = np.arange(len(datasets))
width = 0.25

# Get ResNet-50 baseline
resnet_accs = [df_5shot[(df_5shot['backbone'] == 'resnet50') &
                        (df_5shot['dataset'] == d)]['accuracy'].values[0]
               for d in datasets]

for i, backbone in enumerate(['dinov2_vitb14', 'clip_vitb16', 'vit_base_patch16_224_in21k']):
    if backbone == 'resnet50':
        continue

    accs = [df_5shot[(df_5shot['backbone'] == backbone) &
                     (df_5shot['dataset'] == d)]['accuracy'].values[0]
            for d in datasets]

    improvements = [a - r for a, r in zip(accs, resnet_accs)]

    ax.bar(x + i * width, improvements, width,
           label=BACKBONE_NAMES[backbone],
           color=COLORS[backbone], alpha=0.85)

ax.set_xlabel('Dataset')
ax.set_ylabel('Improvement over ResNet-50 (%)')
ax.set_title('5-Shot: Accuracy Improvement over ResNet-50 Baseline')
ax.set_xticks(x + width)
ax.set_xticklabels([DATASET_NAMES[d] for d in datasets])
ax.legend(loc='upper right')
ax.grid(True, alpha=0.3, axis='y')
ax.axhline(y=0, color='black', linestyle='-', linewidth=0.5)

plt.tight_layout()
fig_path = os.path.join(FIGURES_DIR, 'fig5_improvement.pdf')
plt.savefig(fig_path, bbox_inches='tight')
plt.savefig(fig_path.replace('.pdf', '.png'), bbox_inches='tight')
print(f"✅ Saved: {fig_path}")
plt.show()

# ══════════════════════════════════════════════════════════════
# SUMMARY
# ══════════════════════════════════════════════════════════════

print("\n" + "=" * 60)
print("📊 ALL FIGURES GENERATED!")
print("=" * 60)
print(f"📁 Saved to: {FIGURES_DIR}")
print("\nFiles created:")
for f in sorted(os.listdir(FIGURES_DIR)):
    print(f"   ✅ {f}")